// This helps avoid conflicts in case we inject
// this script on the same page multiple times
// without reloading.

var injected = injected || (function () {

        // An object that will contain the "methods"
        // we can use from our event script.
        var methods = {};

        methods.updateNativeBranding = function (p) {
            let brandingObjectArray = [
                {"title": "Hot or Not: Europeans Named the Hottest on the Sand","branding": "Expedia"},
                {"title": "Should we save each child separately or together for the whole family?","branding": "Bank Leumi"},
                {"title": "Want to become photo wizards? That's where we begin","branding": "Leumiblog"},
                {"title": "Earning more than 25k/month? Instant approval for a credit card. Apply Now!","branding": "Citi Bank"},
                {"title": "5 Things You Need to Know About Taking an Ancestry DNA Test","branding": "Ancestry"},
                {"title": "20 minutes a day is enough to learn a language with this App","branding": "Babbel"},
                {"title": "If You're A Guy Who Hates Buying Clothes, Try Bombfell","branding": "Bombfell"},
                {"title": "How can you improve your beauty routine in 5 simple steps","branding": "Dollar shaveclub"},
                {"title": "Celebrity Street Style : Go-To Loafers from this cult favorite","branding": "Everlane"},
                {"title": "Expedia Analysis: How to Plan a Summer Vacation Without Breaking the Bank","branding": "Expedia"},
                {"title": "Glasses-Wearers Are Going Crazy Over This Website","branding": "Glasses USA"},
                {"title": "Book Cheap Vactions Packages | save 35%","branding": "Kayak"},
                {"title": "2019 Toyotas Worth Considering, and Why","branding": "KBB"},
                {"title": "Get Your Wardrobe Ready For Summer at Macy's","branding": "Macys"},
                {"title": "Nissan NAVARA. Ready for everything. Try it.","branding": "Nissan"},
                {"title": "A multi award winning hybrid mattress - here's why","branding": "Otty"},
                {"title": "Summer is coming ! Give yourself new jewels!","branding": "Pandora"},
                {"title": "7 Reasons Why Meal Kits Are Trendier Than Ever","branding": "Plated"},
                {"title": "How can you increase your productivity today?","branding": "Salesforce"},
                {"title": "Discover the most affordable luxury travel in the world","branding": "Secret escape"},
                {"title": "Stay Stylish And Active With Macy's Latest Athletic Wear","branding": "Macys"},
                {"title": "10 Photos That Will Make You Want to Jet Off and Travel","branding": "TUI"},
                {"title": "Hot or Not: Europeans Named the Hottest on the Sand","branding": "Expedia"},
                {"title": "Our jewels are like memories: capture yours!","branding": "Pandora"},
                {"title": "Shop every style of furniture and décor at up to 70% OFF","branding": "Wayfair"},
                {"title": "How to Qualify for a $400 Bonus Offer. Learn More.","branding": "WellsFargo"},
                {"title": "How to Create Your New Website in 20 Minutes?","branding": "Wix"},
                {"title": "Earn Passive Income with Alternative Investments","branding": "Yieldstreet"},
                {"title": "Fitbit Just Announced The Gadget Of Your Dreams","branding": "Fitbit"},
                {"title": "Bose’s Latest Bluetooth Headphones Don’t Disappoint","branding": "Bose"},
                {"title": "Why an Ancestry® Gift Membership Is the Perfect Holiday Gift","branding": "Ancestry"},
                {"title": "KN95 Face Mask (Pack of 10)","branding": "Brave New Look"},
                {"title": "Find savings on the Pacifica Hybrid for sale near you","branding": "Edmunds"},
                {"title": "How One Woman Made Her Morning Routine More Eco-Conscious","branding": "Elle"},
                {"title": "How To Shop For Summer Skincare Like A Derm","branding": "Elle"},
                {"title": "Celebrities at Home in the '70s: The Photos","branding": "Esquire"},
                {"title": "The next corporate sustainability goal: Capturing all of the CO2 a company has ever emitted","branding": "Fast Company"},
                {"title": "These Are The Best Blowout Deals In Used Hertz Rental Cars","branding": "Forbes"},
                {"title": "40 Photos of Your Favorite TLC Stars Then and Now","branding": "Good Housekeeping"},
                {"title": "The Greatest Gowns That Queen Elizabeth, Meghan Markle, and More Royals Have Worn","branding": "Harpers Bazaar"},
                {"title": "Top 10 Food and Nutrition Trends on the Horizon for 2021","branding": "Healthline"},
                {"title": "60 Charming American Towns Worth Taking a Road Trip to Visit","branding": "House Beautiful"},
                {"title": "Princess Charlotte Gets Cuter by the Day","branding": "Marie Claire"},
                {"title": "Resources for small and medium-size businesses","branding": "Microsoft"},
                {"title": "Get even more with a NerdWallet account","branding": "Nerd Wallet"},
                {"title": "Mattress In A Box UK | Memory Foam Mattresses In A Box | OTTY Sleep","branding": "Otty"},
                {"title": "Vikings: War of Clans - Free Strategy MMO Game | Play Online in Browser","branding": "Plarium"},
                {"title": "The 6 Best Gaming Chairs That Provide Comfort and Support","branding": "Popular Mechanics"},
                {"title": "Purple - The World's First Comfort Tech Company Backed by Science","branding": "Purple"},
                {"title": "7 Ways You Could Accidentally Be Making Your IBS Worse","branding": "Self"},
                {"title": "69 Vintage Photos of Celebrities at the Beach","branding": "Town & Country"},
                {"title": "No cost maintenance plan and roadside assistance.","branding": "Toyota"},
                {"title": "We’re here to support you during these uncertain times","branding": "Wells Fargo"},
                {"title": "Paid Program: More Clarity in Commercial Real Estate","branding": "WSJ"},
                {"title": "¿Cuáles son las carreras mejor pagadas en CDMX?","branding": "OCC"},
                {"title": "¿Necesitás un auto para generar ganancias?","branding": "Uber"},
                {"title": "¿Querés ser el primero en enterarte cuando hay vuelos baratos a Barcelona?","branding": "Turismo City"},
                {"title": "4 malos hábitos que deberías evitar por las mañanas","branding": "Runtastic"},
                {"title": "48 Horas Peugeot del 14 al 16 de marzo","branding": "Peugeot"},
                {"title": "5 cosas que puedes hacer con la leche, además de tomarla","branding": "Colanta"},
                {"title": "5 negocios rentables para este 2020","branding": "Futuro Emprendedor"},
                {"title": "Conoce las ofertas de equipos de descanso de Lo Mónacoz","branding": "Lo Monaco"},
                {"title": "5 preguntas frecuentes sobre la nube de Oracle","branding": "Oracle"},
                {"title": "A donde quiera que vayas, MAPFRE va de tu lado. Asegura tu auto desde $5,999","branding": "Mapfre"},
                {"title": "Acogedora, cómoda, dinámica y desempeño en cada curva y cada kilómetro, así es la Creta.","branding": "Hyundai"},
                {"title": "Asegura tu coche con las mejores condiciones","branding": "AXA"},
                {"title": "Así es cómo los más de 150 expertos en idiomas de Babbel crean una app científicamente probada","branding": "Babbel"},
                {"title": "Balance entre tu vida laboral y personal","branding": "AT&T"},
                {"title": "Cómo protege Airbnb a sus anfitriones","branding": "Air bnb"},
                {"title": "Conoce las ofertas de equipos de descanso de Lo Mónaco","branding": "Lo Monaco"},
                {"title": "Contrata Fibra + 2 Líneas Móvil x 16,90€ mes ! Para Siempre !","branding": "MásMovil"},
                {"title": "Contrata Servigas de Naturgy con 10% dto.","branding": "Gas Natural"},
                {"title": "Conviértete en un anfitrión de Airbnb y gana dinero","branding": "Airbnb"},
                {"title": "definiendo conceptos: qué es el emprendimiento","branding": "Futuro Emprendedo"},
                {"title": "Desalación por ósmosis inversa, el mar como fuente de esperanza","branding": "Experience Acciona"},
                {"title": "Descubre en segundos si La Tarjeta es Pre aprobada","branding": "American Express"},
                {"title": "Descubre los 5 sencillos pasos para comprar una casa con...","branding": "Javer"},
                {"title": "Descubre Solana, la tienda online de Mahou San Miguel","branding": "Mahou"},
                {"title": "El hotel de tus sueños al mejor precio.","branding": "Hotel Scan"},
                {"title": "Encuentra habitación buena, bonita y barata","branding": "Badi"},
                {"title": "Estrena un Cadillac y adquiere miles de Puntos Premier","branding": "Cadillac"},
                {"title": "Estudia en línea con Validez Oficial de estudios una Licenciatura, Maestría, Máster o Doctorado..","branding": "Utel"},
                {"title": "i20 ¿Quieres un auto refinado y elegante? ¡Hazlo realidad ahora!","branding": "Hyundai"},
                {"title": "Incluir a Cruz Roja en tu Testamento nos permitirá continuar con nuestro proyecto.","branding": "Cruz Roja"},
                {"title": "La SUV que está a la vanguardia del progreso","branding": "Toyota"},
                {"title": "Leyendas de Turquía Hierápolis y el “Castillo de Algodón”","branding": "Mundomex"},
                {"title": "Los comunicadores deben ser capaces de gerenciar","branding": "ORT"},
                {"title": "Magíster en Administración de Empresas con Especialidad en Gerencia de Proyectos","branding": "UVirtual"},
                {"title": "Magíster en Administración de Empresas con Especialidad en..","branding": "UNAP"},
                {"title": "Mujeres en AT&T México","branding": "AT&T"},
                {"title": "Negocios Te decimos cómo hacer correctamente el inventario de tu","branding": "Oikos Storage"},
                {"title": "No necesitas coche para ganar dinero","branding": "Uber"},
                {"title": "Promociones y ofertas de Autos, Camionetas y SUVs","branding": "Volkswagen"},
                {"title": "Reduce tu Pago total de Tarjetas de Credito desde un 30% hasta un 50%.","branding": "Consolidated Credit"},
                {"title": "Renueva tu caldera con Saunier Duval. ¡Recibe presupuestos en menos de 24 horas!","branding": "Saunier Duval"},
                {"title": "Sorteamos una cafetera Dedica de Delonghi por el día del Padre","branding": "Delonghi"},
                {"title": "Tecnología skyactiv® de mazda: un enfoque más inteligente","branding": "Mazda"},
                {"title": "Test: ¡Lo que tu película favorita de Marvel dice sobre ti!","branding": "A&E"},
                {"title": "TLX , Lujo auténtico desde $3,715* mensuales, ¡Regístrate!","branding": "Honda"},
                {"title": "Tú eliges para qué quieres ahorrar con Mutuactivos","branding": "Mutua Madrileña"},
                {"title": "Tu seguro de coche ahora con seis meses gratis‎.","branding": "Just Fab"},
                {"title": "Un híbrido en la ciudad es el mejor calmante del mundo","branding": "Toyota"},
                {"title": "Una glicinia de 144 años, japón","branding": "Do days do"},
                {"title": "Vende tu casa con Housell, sin exclusividad","branding": "Housell"},
                {"title": "Vive el encanto de Oporto - Viaja ahora desde 69€","branding": "Iberia"},
                {"title": "Microsoft Edge, alışveriş yapmak için en iyi tarayıcıdır","branding": "Microsoft"},
                {"title": "Kendine saygısı olan kadınların giymemesi gereken 20 kıyafet","branding": "LuxuryLevels.com"},
                {"title": "Şile’de, şehre yakın ama kalabalıktan uzak tatil fırsatları…","branding": "Odamax"},
                {"title": "Seren Serengil kuaförden makyajsız halini paylaştı görenler şok oldu","branding": "Lawyers Favorite"},
                {"title": "Cemile Dantel Luster Füme 6'lı 20,5 cm Servis Gereçleri","branding": "Boyner"},
                {"title": "İstanbul seyahatin için aradığın oteli kolayca bul!","branding": "Odamax"},
                {"title": "DoubleTree by Hilton Antalya City Center | Odamax.com","branding": "Odamax"},
                {"title": "Brigitte Bardot Yaş Alsa da Hala Eskisi Kadar Güzel Olduğunu Bu Resimlerle Kanıtladı!","branding": "TummyTuckHipo"},
                {"title": "Bitcoin piyasasına katılın ve finansal geleceğinizi garanti altına alın.","branding": "MTM"},
                {"title": "Kazancın Fazla Olduğu Yatırımlar Nelerdir?","branding": "Yatırım"},
                {"title": "Acun Ilıcalı 7,5 milyonluk yeni arabasıyla görüldü","branding": "Trading Blvd"},
                {"title": "Kredide Fırsat! Ayda 382 TL'ye 10.000 TL'yi Kaçırma!","branding": "Hangikredi.com"},
                {"title": "Bambum Zolla - Küçük Cam Saklama Kabı","branding": "Boyner"},
                {"title": "İstanbula Yakın Oteller ve İstanbula Yakın Otel Fiyatları | Etstur.com","branding": "Etstur"},
                {"title": "Tamamen Yenilenen Yeni Ford Kuga","branding": "Ford"},
                {"title": "Abant’ta doğa ile baş başa tatilin tadını çıkar!","branding": "Odamax"},
                {"title": "Eşi bu fotoğrafa baktıktan sonra karısına boşanma davası açtı","branding": "LightAndCharm.com"},
                {"title": "Herkesin mutlaka bilmesi gereken mükemmel bir WD40 ipucu","branding": "Fresh-Story.com"},
                {"title": "Asics 1022A189-700 Gel-Bnd Koşu Ayakkabısı","branding": "Boyner"},
                {"title": "Aile fotoğrafını gördükten sonra karısından boşanmak istedi","branding": "Bright-Story"},
                {"title": "OneDrive Kişisel Bulut Depolama Alanı","branding": "Microsoft"},
                {"title": "Bu Oyunu 1 Dakika boyunca oynayın ve neden herkesin bağımlı olduğunu görün","branding": "Desert Order (Strateji Oyunu)"},
                {"title": "Microsoft Teams herkese yöneliktir","branding": "Microsoft"},
                {"title": "Braun Multiquick MQ535 Aperitive 600W Blender","branding": "Boyner"},
                {"title": "Altınyıldız Classic Standart Fit Bisiklet Yaka Jakarlı Triko Kazak","branding": "Boyner"},
                {"title": "Yepyeni Ford Puma. Stil sahibi olman için tasarlandı.","branding": "Ford"},
                {"title": "Microsoft 365 ile daha fazlasını yapın","branding": "Microsoft"},
                {"title": "Ford Courier Journey’i kiralama fırsatı Ford Lease’de.","branding": "Ford"},
                {"title": "Binlerce Tesiste Hızlı Rezervasyon - Odamax.com | Odamax.com","branding": "Odamax"},
                {"title": "Çekici Serisi Çekemediği Bir Tek Hasret","branding": "Ford"},
                {"title": "Sizin de kaskonuz muafiyetli ama haberiniz mi yok?","branding": "Generali Sigorta"},
                {"title": "Popüler İsim Arabasını Bitcoin Karşılığında Sattı","branding": "Coin News"},
                {"title": "Xperia Saray Beach Hotel | Odamax.com","branding": "Odamax"},
                {"title": "Windows 10 nasıl kullanılır?","branding": "Microsoft"},
                {"title": "Kapadokya Otelleri | Etstur","branding": "Etstur"},
                {"title": "Ford Güncel Otomobil Kampanyaları","branding": "Ford"},
                {"title": "Anil Transparan Detaylı 2'li Çamaşır Takımı","branding": "Boyner"},
                {"title": "Antalya'da deniz ve güneşle buluş!","branding": "Odamax"},
                {"title": "adidas Basketbol Ayakkabısı","branding": "Etstur"},
                {"title": "adidas Lifestyle Ayakkabı","branding": "Etstur"},
                {"title": "Offerte gas e luce a confronto: ecco le tariffe più convenienti","branding": "Compara&Risparmia"},
                {"title": "I giocatori di tutto il mondo hanno atteso questo gioco!","branding": "Forge of Empires - Free Online Game"},
                {"title": "Vuoi comprare un montascale? Considera altre possibilità!","branding": "Offerte di Montascale | Ricerca annunci"},
                {"title": "Offerte auto ibride: -50% questo mese!","branding": "Auto Ibride | Ricerca Annunci"},
                {"title": "Offerta luce: confrontiamo TUTTE le tariffe dei fornitori. Da 18€/mese","branding": "ituoicorsi.com"},
                {"title": "Guida al testamento solidale: come fare per aiutare anche con poco 70 milioni di rifugiati","branding": "UNHCR"},
                {"title": "Il potente rimedio che sgonfia il corpo e brucia i grassi","branding": "Slimberry"},
                {"title": "L'aereo più grande della storia militare","branding": "Post Fun"},
                {"title": "Figli famosi: indovina chi è il genitore vip!","branding": "Alfemminile"},
                {"title": "Polizza online RCA, guida sereno scegliendo l'assicurazione che fa per te","branding": "Quale.it"},
                {"title": "5-49 Veicoli? Questo dispositivo sta rivoluzionando il mondo delle auto","branding": "Expert Market"},
                {"title": "Questa app è come Amazon. Ma vende tutto al prezzo di fabbrica","branding": "Scarica L'App | Vova"},
                {"title": "Suv 2019: offerta -50% e rate da € 100","branding": "Offerte Suv | Ricerca Annunci"},
                {"title": "Auto Ibride del 2018, trova offerte al -50%","branding": "Auto Ibride | Ricerca annunci"},
                {"title": "Quanto costa un montascale?","branding": "Montascale | Ricerca annunci"},
                {"title": "Lo SmartWatch a soli 59€ boom di vendite in Italia","branding": "xPower Watch™"},
                {"title": "Pescatori trovano qualcosa di strano su un iceberg","branding": "Give It Love"},
                {"title": "Vuoi richiedere una Green Card degli Stati Uniti? Verifica gratuitamente","branding": "U.S Green Card"},
                {"title": "¿Recuerdas al hijo de Sandra Bullock? Trata de no impresionarte cuando veas cómo se ve ahora","branding": "LawyersFavorite"},
                {"title": "Ecco cosa accadrebbe dormendo con dell'aglio sotto il cuscino","branding": "Bright Story"},
                {"title": "Vuoi liberarti dalle Rughe?","branding": "FaceSolutions"},
                {"title": "Approvati prestiti veloci per dipendenti pubblici e statali a tasso agevolato","branding": "Prestito per Dipendenti Pubblici e Statali"},
                {"title": "Milan Offerte SUV Nuovi - Tutto quello che cerchi","branding": "Occasioni SUV | Ricerca Annunci"},
                {"title": "Intervento Laser Occhi: tassi agevolati e comode rate","branding": "Clinica Baviera"},
                {"title": "Ti senti solo in Italia? Prova questi siti di incontri","branding": "I 5 migliori siti di incontri"},
                {"title": "SUV con il miglior rapporto qualità-prezzo: la classifica aggiornata","branding": "SUV economici | Ricerca Annunci"},
                {"title": "Assicurazioni Auto Economiche, Ecco i Prezzi Migliori!","branding": "Assicurazione Auto | Ricerca Annunci"},
                {"title": "Ecco le extension che puoi mettere e togliere senza andare dal parrucchiere","branding": "BenessereBio"},
                {"title": "Questa micro-camera è davvero incredibile: Registra video in HD ovunque","branding": "CopCam"},
                {"title": "6 Passaggi Hard-Core per Andare in Pensione Giovani","branding": "eurobenne.it"},
                {"title": "Migliaia di italiani stanno acquistando gli orologi meccanici di questa startup svizzera","branding": "Orologio CODE41"},
                {"title": "La nuova spezia sgonfiante già record di vendite in Italia","branding": "Oggi Benessere"},
                {"title": "Coppia adotta cane randagio: una trasformazione incredibile","branding": "Give It Love"},
                {"title": "Metti una tazza di riso nel guardaroba ed ecco quello che succede","branding": "Factaholics"},
                {"title": "Gli archeologi hanno appena fatto una scoperta inaspettata sull'isola di Pasqua","branding": "Bridozia"},
                {"title": "Approvati prestiti per dipendenti pubblici e statali a tasso agevolato in convenzione","branding": "Prestito per Dipendenti Pubblici"},
                {"title": "Dal grave incidente alla truffa: le cose da sapere su Alda D'Eusanio","branding": "Donnaglamour.it"},
                {"title": "Il padre muore poco prima del matrimonio di sua figlia, ma quando lei si gira, scoppia in lacrime","branding": "DailyChasers"},
                {"title": "Vi ricordate di lei? 15 star morte troppo presto...","branding": "momento.it"},
                {"title": "Elimina i fibromi penduli con un metodo facile e indolore!","branding": "Consigli e Trucchi"},
                {"title": "Grazie a questo semplice trucco, potrete pulire i vostri fornelli in 2 minuti","branding": "DailyHolics"},
                {"title": "I migliori bassisti di sempre","branding": "Post Fun"},
                {"title": "La soluzione ai cavi aggrovigliati delle cuffie è arrivata! Nuove cuffie wireless Bluetooth i7s!","branding": "i7s Wireless Earphones"},
                {"title": "Elimina il grasso addominale con questo nuovo dispositivo","branding": "X-Power Trainer"},
                {"title": "Почувствуй себя колонизатором!","branding": "XCraft"},
                {"title": "Приглядевшись к этой фотографии, мужчина решил подать на развод!","branding": "WorldRazor"},
                {"title": "В чем налоговая подозревает ИП на УСН: знай и избегай","branding": "Sovcom.pro [16+]"},
                {"title": "Представляем 30 самых красивых женщин мира","branding": "LifeStly.com"},
                {"title": "20 рецептов здорового завтрака, которые поднимут настроение","branding": "TheWorldReads.com"},
                {"title": "Это то, что ваше положение во сне может рассказать о вас","branding": "Women's Method"},
                {"title": "10 Фактов О Влиянии Кошек На Здоровье Человека","branding": "the-best-info"},
                {"title": "Жена Серхио Рамоса вероятно самая красивая женщина на земле","branding": "Story-Wiki.com"},
                {"title": "Mansion New от Katepal – это больше, чем двухслойная черепица!","branding": "KATEPAL [16+]"},
                {"title": "Самые Красивые Розы На Свете","branding": "Info-Incredible"},
                {"title": "10 Фактов О Влиянии Кошек На Здоровье Человека","branding": "the-best-info"},
                {"title": "Топ 10 самых умных пород собак","branding": "Cool Posts"},
                {"title": "Киркоров вывел в свет мать своих детей! Мы все ее знаем","branding": "News Sphere"},
                {"title": "Самые невероятные фотографии в Северной Корее # 10 ужасает","branding": "The Travel Breeze"},
                {"title": "Ночные судороги ног: очень плохой сигнал организма","branding": "News Sphere"},
                {"title": "Эта женщина в инвалидной коляске не могла подняться по лестнице, но посмотр","branding": "полезные советы"},
                {"title": "Вот почему все замораживают лимоны после их покупки! Замороженные лимоны","branding": "Home Tricks"},
                {"title": "Что ваша поза во сне говорит о вашей личности","branding": "Women's Method"},
                {"title": "Такой легкий трюк: как открыть консервную банку без помощи консервног","branding": "полезные советы"},
                {"title": "30 самых красивых женщин в мире","branding": "LifeStly.com"},
                {"title": "Топ-10 самых богатых женщин российского шоу-бизнеса","branding": "Cool Pages"},
                {"title": "Новорожденный впервые открыл глаза – его мать оцепенела от ужаса","branding": "Mom Life Matters"},
                {"title": "Годами жил под маской лжи: жена раскрыла тайну Кобзона","branding": "News Sphere"},
                {"title": "5 признаков, что COVID у вас уже был и прошел сам","branding": "News Sphere"},
                {"title": "Избавляемся от седых волос естественным образом","branding": "good news"},
                {"title": "Ешьте соленые огурцы каждый день. Вот каким будет результат через месяц","branding": "Facts 2 Read"},
                {"title": "Градостроительная игра которая позволяет тебе играть сквозь века","branding": "Кузница Империй | Играй Бесплатно [16+]"},
                {"title": "20 продуктов, которые медленно вас убивают","branding": "TheWorldReads.com"},
                {"title": "Решили бросить курить? Табекс - №1, чтобы бросить!","branding": "Есть противопоказания | Tabex [18+]"},
                {"title": "Какой метод контрацепции подходит именно тебе?","branding": "Какой метод контрацепции подходит именно тебе?"},
                {"title": "Эта 96-летняя дама продает свой дом. Вы упадете со стула, увидив обстановку внут","branding": "Happy-Tricks.com"},
                {"title": "11 знаменитостей с позитивным телом, которые нас вдохновляют","branding": "DeltaNews"},
                {"title": "Школьник случайно раскрыл секрет своего отца – его с родителями вызвали в больницу","branding": "Daily Motivation"},
                {"title": "Идеальный способ очистить матрас от всех загрязнений","branding": "HouseTricks"},
                {"title": "Женщина бросила своего мужа – лишь через 60 лет он узнал, почему!","branding": "Love What Matters"},
                {"title": "Плохо спите? Эти пять растений обязательно помогут!","branding": "Better Lifehacks"},
                {"title": "Стоимость дентальных имплантатов в Брянск может вас удивить","branding": "имплант зуба | рекламные ссылки"},
                {"title": "Ваши любимые premium бренды на Lamoda","branding": "lamoda.ru"},
                {"title": "2-летний ребенок остался дома с собакой – когда вернулись родители, они сразу же вызвали полицию!","branding": "Daily Stage"},
                {"title": "Как привести газовую конфорку в идеальную чистоту за минуту…","branding": "House Tricks"},
                {"title": "Женщина сфотографировала своего ребенка и собаку. Вдруг животное сделало то, что мать никогда не забудет","branding": "Everyday Matters"},
                {"title": "Младенец остался дома с собакой – когда вернулась мама, она об этом сильно пожалела…","branding": "Facts2Read"},
                {"title": "Ешьте чеснок одну неделю, и увидите, что будет!","branding": "Better Lifehacks"},
                {"title": "Топ 10 Самых Красивых Роз в Мире","branding": "Info-Incredible"},
                {"title": "Максимальный комфорт с аэролодкой Север","branding": "SeverBoat [16+]"},
                {"title": "Купить женские платья недорого в GroupPrice. Интернет-магазин выгодных п","branding": "groupprice.ru [16+]"},
                {"title": "Вас ждет отпуск, который превзойдет все ваши ожидания!","branding": "Gloria Hotels & Resorts"},
                {"title": "รับประทานไข่เพียงวันละ 3 ฟอง ชีวิตจะไม่เหมือนเดิมอีกต่อไป","branding": "Healthsupportmag"},
                {"title": "เกมสมจริงที่สุด ฟรีต้องลอง ไม่โหลดไม่ได้แล้ว","branding": "Plarium"},
                {"title": "ถ้ามีคอมพิวเตอร์ ต้องไม่พลาดเกมนี้","branding": "Plarium"},
                {"title": "ฝาแฝดเด็กที่สวยที่สุดในโลก","branding": "Women Tales"},
                {"title": "เผยโฉม ฟอร์ด เรนเจอร์ และเอเวอเรสต์ใหม่ เสริมลุคดุดัน เพิ่มสไตล์สปอร์ต","branding": "Autodeft"},
                {"title": "ทำไมต้องรับประทานไข่วันละ 3 ฟอง?","branding": "Healthsupportmag"},
                {"title": "ช่องทางที่ดีที่สุดในการซื้อและขายรถยนต์มือสอง","branding": "Carsome"},
                {"title": "ที่สุดของผลิตภัณฑ์บำรุงผิวเพื่อลดริ้วรอยและจุดด่างดำจากประเทศญี่ปุ่น ที่ผ่านการวิจัยมากว่า 40 ปี","branding": "Domohorn Wrinkle"},
                {"title": "‘ซูซูกิ’เดินหน้ารุกขยายธุรกิจรองรับการเติบโต เปิดตัวผู้จำหน่ายใหม่มากถึง 19 แห่ง","branding": "Siamsport"},
                {"title": "ยามาฮ่า เปิดตัวทีมแข่ง “มอนสเตอร์ เอเนอร์จี ยามาฮ่า โมโตจีพี” คว้าตัว กวาตาราโร่ ผนึกกำลัง บีญาเลส","branding": "Siamsport"},
                {"title": "ปรับ New Look ให้บ้าน ต้อนรับ New Year","branding": "Design Square"},
                {"title": "Big Thanks Sale เฟอร์นิเจอร์ลดเพิ่ม 15%","branding": "Design Square"},
                {"title": "ช่องทางการขายรถที่สะดวก เชื่อถือได้ และจ่ายเงินไวใน 1 ชั่วโมง","branding": "Carsome"},
                {"title": "ชุดห้องนอน ขนาด 6 ฟุต รุ่น Backus สีโอ๊ค พร้อมโซฟา Manner","branding": "Design Square"},
                {"title": "보청기 국가지원 받아 구매해요","branding": "hear.com"},
                {"title": "같은 보장인데 보험료가 다른 이유는? 알고보니..","branding": "바로비교"},
                {"title": "시서스 다이어트 진작 할걸.. 꽉 찬 '지방' 몰라보게 뺀다!","branding": "시서스 올핏 다이어트"},
                {"title": "5月 긴급생계지원금 인당 '1억원'까지.. 나만 몰랐다!","branding": "해피드림론"},
                {"title": "나에게 맞는 실비보험 상품, 골라서 저렴하게 가입하자.","branding": "바로비교"},
                {"title": "유진도 선택한 듀얼소닉, 4주 후 피부 속탄력 94.4% 상승!","branding": "DUALSONIC"},
                {"title": "하루10분 간단히 하는 리프팅 케어, 비결은?","branding": "Zombiebeatuy"},
                {"title": "나만 몰랐다! 서민 긴급자금 풀렸더니.. 사람들이 신청한 \"이것\" 문의폭주!!","branding": "우리드림론"},
                {"title": "긴급 생계자금 햇살론 풀렸다.. 최대 1억까지 가능한 서민대출!","branding": "위더스론"},
                {"title": "혼공이 점점 잡혀가서 엄마로써 만족해요","branding": "웅진 스마트올중학"},
                {"title": "건강하게 오래 살고 싶다면 피해야 할 음식 20가지","branding": "Word Daily Life.com"},
                {"title": "고혈압 당뇨 지긋한 약 끊고 정상수치 돌아와","branding": "리턴큐"},
                {"title": "로또 매일 4천원 이상 산다면 '이것' 기억해..","branding": "로또리드"},
                {"title": "풍성해지니까 자신감이 생겼어요","branding": "모모단"},
                {"title": "긴급 생계, 대환대출.. 최대 1억까지! 당일입금 내 한도는?","branding": "서민토탈론"},
                {"title": "당신에게 놀라움을 선사하는 매트리스 가격","branding": "매트리스 | 검색 광고"},
                {"title": "2021 년은 마침내 새로운 임플란트를 얻을 수있는 해가 될 것입니다.","branding": "치과 임플란트 | 검색 광고"},
                {"title": "연예인 극찬!! 온가족 보습 고민 한번에 끝!!","branding": "카테고리"},
                {"title": "이달의 차! 쉐보레 트레일블레이저","branding": "Chevrolet"},
                {"title": "심리테스트로 내 배우자 얼굴 예측하기.","branding": "노블레스 수현"},
                {"title": "물이 만든 아름다운 경관들","branding": "MSN"},
                {"title": "전국민 생계자금 최대 1억원 지원, 연 3.9% 모바일신청 오늘 마감","branding": "국민 금융"},
                {"title": "통합대출 긴급자금 풀렸다!! 당일 입금! 내한도랑 금리는 얼마?","branding": "착한나누미론"},
                {"title": "신형 K7 장기렌트, 무보증 월 492,470원에 탄다?","branding": "rentrun"},
                {"title": "당신이 원하는 '급등주' ! 지금 확인하세요","branding": "여의도스탁"},
                {"title": "Formation payée : Comment les Français en profitent ?","branding": "Lecole francaise"},
                {"title": "Vacances les pieds dans l'eau","branding": "Out of office"},
                {"title": "Coffret Dégustation Gourmet","branding": "Foiegras gourmet"},
                {"title": "Tout sur la cannelle, l'épice star des Fêtes | Foodspring Magazine","branding": "Foodspring"},
                {"title": "Montres | Kapten & Son","branding": "Kapten & Son"},
                {"title": "Forfaits Cellulaires - Comparez les meilleurs plans pas chers","branding": "Planhub"},
                {"title": "Shape Shake 2.0","branding": "Foodspring"},
                {"title": "Ces formations à domicile financées pour tous les Français","branding": "Lecole francaise"},
                {"title": "Tout sur la cannelle, l'épice star des Fêtes | Foodspring Magazine","branding": "Foodspring"},
                {"title": "Quel est le Prix d'une Assurance vie 50 ans et plus? Et l’assurance vie pour 55 ans et +?","branding": "Comparer assurancevie"},
                {"title": "35 Astuces pour que la Décoration de Votre Maison ait l'Air Chère","branding": "The fashion ball"},
                {"title": "Pâte à Tartiner Protéinée","branding": "Foodspring"},
                {"title": "Les 3 plus beaux hôtels de la montagne","branding": "Out of office"},
                {"title": "Les foies gras préférés des expatriés français pour les fêtes de fin d’année","branding": "Foiegras gourmet"},
                {"title": "Sacs à dos | Kapten & Son","branding": "Kapten & Son"},
                {"title": "La première balade de l'hiver","branding": "Gustave et rosalie"},
                {"title": "Vacances farniente à Saint-Martin","branding": "Out of office"},
                {"title": "Pâte à Tartiner Protéinée","branding": "Foodspring"},
                {"title": "אפליקציית המכרזים שמצמיחה עסקים - כל המכרזים ובכל התחומים","branding": "Marketism - Ifat michrazim"},
                {"title": "הכירו את ה-SUV החשמלי שמאובזר בשלל מערכות בטיחות אקטיביות מקוריות","branding": "Union - Peugeot"},
                {"title": "הכל יחסי – בואו לגלות איזה רכב פנאי ניצח את כל האחרים","branding": "Union - Peugeot"},
                {"title": "רק נשמע יקר: לא תאמינו כמה קל להתקדם לרכב חשמלי כבר עכשיו","branding": "GAC"},
                {"title": "קיה ספורטאז' - הכירו את רכב הפנאי המוביל בישראל עם אחד מדירוגי הבטיחות הגבוהים בקטגוריה","branding": "Dentsu Aegis IL - Kia"},
                {"title": "מאזדה CX-30 הקרוסאובר המשפחתי בימי מכירות 27.11 עד 11.12","branding": "Zenith Digital - Delek"},
                {"title": "הג'יפון החשמלי MG ZS EV במחיר חדש ואטרקטיבי במיוחד","branding": "Brukner Yaar Levi - Lubinski"},
                {"title": "Mercedes-Benz 2021 אירוע מכירות אחרון לשנה 25-17 בדצמבר","branding": "TMF - Mercedes-Benz"},
                {"title": "מארז 3 מכנסי פוטר בהדפסים שונים / 0-6Y","branding": "TerminalX DCO"},
                {"title": "רכב המנהלים הכי אלגנטי בישראל - עכשיו עם יותר כוחות סוס מאי פעם","branding": "TMF - Toyota_General & Select"},
                {"title": "adidas Alphaedge 4D Reflective נעלי ריצה","branding": "Adidas DCO"},
                {"title": "הג'יפון החשמלי MG ZS EV במחיר חדש ואטרקטיבי במיוחד","branding": "Brukner Yaar Levi - Lubinski"},
                {"title": "הפתרון המושלם מבוש להכנת ארוחות מראש ומניעת בזבוז מזון","branding": "TMF - Bosch"},
                {"title": "adidas adidas by Stella McCartney Wash Kit","branding": "Adidas DCO"},
                {"title": "מארז 3 סווטשירטים פוטר בהדפסים / 3M-6Y","branding": "TerminalX DCO"},
                {"title": "adidas Alphabounce Beyond נעלי ריצה","branding": "Adidas DCO"},
                {"title": "אחרי 3 שנים כמכונית המיני הנמכרת ביותר בישראל - אלו החידושים של קיה פיקנטו 2020","branding": "Dentsu Aegis IL - Kia"},
                {"title": "רכב חשמלי: מהיום גם אתה יכול להתקדם ולחסוך עשרות אלפי שקלים","branding": "Dsay - GAC"},
                {"title": "כמה דברים שחשוב לשים לב אליהם רגע לפני שקונים רכב יד שניה","branding": "TMF - TradeIn"},
                {"title": "מבצע החודש באוטו סנטר: קנו עכשיו רכב יד שנייה ותתחילו לשלם רק אחרי החגים","branding": "Shimoni Finkelstein FCB - Auto Center"},
                {"title": "adidas ADILETTE CLOUDFOAM PLUS MONO כפכפי ים","branding": "Adidas DCO"},
                {"title": "השקה יוצאת דופן – קבלו את מכונית היוקרה ששוברת כל מוסכמה","branding": "Union - DS"},
                {"title": "רכבי היוקרה של אינפיניטי: צעד לפני כולם בחדשנות, במחיר ובשירות","branding": "Carasoo Motors"},
                {"title": "המגזין האמריקני המוביל קובע: מאזדה מותג הרכב האמין ביותר","branding": "Zenith Digital - Delek"},
                {"title": "מארז 3 סווטשירטים פוטר בהדפסים שונים / 3M-6Y","branding": "TerminalX DCO"},
                {"title": "אירוע מכירות אחרון לשנה | 25-17 בדצמבר בכל אולמות התצוגה.","branding": "TMF - Mercedes-Benz"},
                {"title": "הרקסטון האהוב עבר שדרוג למכלולי השטח - ברור שלקחנו אותו ראשונים למבחן","branding": "Dentsu Aegis IL - Ssangyong"},
                {"title": "זאת לא מכונית, זה טיל. והוא לא צורך טיפת דלק - פורשה טייקן","branding": "Rabak - Porsche Israel"},
                {"title": "הכירו את מבצע החודש לרכבי יד שנייה באוטו סנטר: קנו היום, תתחילו לשלם רק בעוד 3 חודשים","branding": "Shimoni Finkelstein FCB - Auto Center"},
                {"title": "מרצדס-בנץ משיקה: EQC המרצדס החשמלית הראשונה בישראל","branding": "TMF - Colmobil Commercials"},
                {"title": "מרצדס-בנץ EQC משלבת שני מנועים חשמליים מתקדמים עם הנעה כפולה","branding": "TMF - Mercedes-Benz"},
                {"title": "עולם הרכב הולך ומתקדם לעידן של רכב חשמלי, רוצים לדעת מתי? היכנסו","branding": "TMF - Toyota_General & Select"},
                {"title": "לא עוד מכונית יוקרה קונבנציונלית. ה-DS 7 CROSSBACK הינה קלאסיקה צרפתית","branding": "Union - DS"},
                {"title": "adidas AlphaEdge 4D - Star Wars נעלי ריצה","branding": "Adidas DCO"},
                {"title": "הקרוסאובר ההמשפחתי הכי מדהים על הכביש - יצאנו לבדוק אותו","branding": "Zenith Digital - Delek"},
                {"title": "מארז 3 סווטשירטים פרנץ' טרי בהדפסים שונים / ילדים","branding": "TerminalX DCO"},
                {"title": "אפליקציית המכרזים שמצמיחה עסקים - כל המכרזים ובכל התחומים","branding": "Marketism - Ifat michrazim"},
                {"title": "הרקסטון האהוב עבר שדרוג למכלולי השטח - ברור שלקחנו אותו ראשונים למבחן","branding": "Dentsu Aegis IL - Ssangyong"},
                {"title": "קיה ספורטאז' - הכירו את רכב הפנאי המוביל בישראל עם אחד מדירוגי הבטיחות הגבוהים בקטגוריה","branding": "Dentsu Aegis IL - Kia"},
                {"title": "adidas ADICOLOR TREFOIL סווטשירט אוריג'ינלס","branding": "Adidas DCO"},
                {"title": "האגיס מגבונים לחים לתינוק, עדין לעור כמו צמר גפן ומים","branding": "SuperPharm DCO"},
                {"title": "הזדמנות אחרונה בפרויקט Agam: דירת יוקרה משלכם ממש על גדת הכנרת","branding": "Marketism - Agam-Yochelman"},
                {"title": "כל מה שחשוב לדעת על הצרכים התזונתיים של הכלב האורבני","branding": "Twisted - BIOPET"},
                {"title": "הכירו את ה-SUV החשמלי שמאובזר בשלל מערכות בטיחות אקטיביות מקוריות","branding": "Union - Peugeot"},
                {"title": "מאזדה CX-30 הקרוסאובר המשפחתי בימי מכירות 27.11 עד 11.12","branding": "Zenith Digital - Delek"},
                {"title": "נחטף כמו לחמניות חמות- יונדאי טוסון יגרום לך להתאהב","branding": "TMF"},
                {"title": "פתרון הוואקום הגאוני של הבלנדר מוט של בוש יחסוך לכם","branding": "TMF - Bosch"},
                {"title": "adidas 3-Stripes מכנסיים אוריג'נלס","branding": "Adidas DCO"},
                {"title": "adidas adidas 4D Run 1.0 Shoes","branding": "Adidas DCO"},
                {"title": "בושם לגבר Club de Nuit Intense","branding": "TerminalX DCO"},
                {"title": "New Kia Stinger Weil der Weg das Ziel ist","branding": "Kia"},
                {"title": "Black is back Elegante Damenmode & Wäsche in Schwarz","branding": "Tchibo"},
                {"title": "Dieser Möbel-Onlineshop wird dich umhauen","branding": "Wayfair"},
                {"title": "Kia e-Niro Elektrisierend und vollelektrisch.","branding": "Kia"},
                {"title": "Strahlend schöne Haut mit Straffung von Falten.","branding": "Haar-shop"},
                {"title": "Tipps und Tricks rund um Konditionstraining","branding": "Otto"},
                {"title": "PhysioLift - Glättet die Haut sichtbar und strafft sie dauerhaft","branding": "Eau-thermale"},
                {"title": "Diese Uhr ist derzeit heiß begehrt bei Influencern","branding": "Kapten-son"},
                {"title": "Dein So-wie-du-willst-Tarif mit unlimited Datenvolumen & Allnet-Flat für nur 39,99 € mtl.*","branding": "O2online"},
                {"title": "Wie schnell dürfen Sie fahren? Hier sehen Sie es – direkt im Display.","branding": "Kia"},
                {"title": "Sneaker von Asics bis zu -67% reduziert. Nur solange der Vorrat reicht","branding": "Limango"},
                {"title": "Angebote-Produkte & Zubehör online kaufen im INTERSPORT-Shop","branding": "Intersport"},
                {"title": "Sichere dir jetzt deine Uhr mit gratis Kulturbeutel","branding": "Kapten-son"},
                {"title": "Jetzt mit 20 GB LTE im o2 Free M für nur 29,99 € mtl.*","branding": "O2online"},
                {"title": "Dein Studium mit 0%-Finanzierung vom Staat: So geht’s!","branding": "Bafög"},
                {"title": "Angst vor Haarausfall? Tun Sie was dagegen.","branding": "Renefurterer"},
                {"title": "Sei mit dem richtigen schuhwerk gerüstet für dein outdoor-abenteuer!","branding": "Intersport"},
                {"title": "Damenmode günstig im ABOUT YOU Sale kaufen","branding": "Intersport"},
                {"title": "Damenmode günstig im ABOUT YOU Sale kaufen","branding": "About You"},
                {"title": "Asics bis zu -67% reduziert! Viele verschiedene Farben und Modelle. Jetzt entdecken","branding": "Limango"},
                {"title": "Angesagte Brands Unsere Lieblingsmarken für Dich","branding": "About You"},
                {"title": "Sichere dir jetzt deinen Rucksack mit bis zu 50 % Rabatt","branding": "Kapten-son"},
                {"title": "Erkunden Sie die wunderbare Welt von Swarovski. Herausragendes Styling seit 1895.","branding": "Swarovski"},
                {"title": "Motivation gefällig?","branding": "aboutyou"},
                {"title": "Zeit zum Pflanzen Hochbeete, Gewächshäuser & Ideen rund ums Gärtnern","branding": "Tchibo"},
                {"title": "Energetics: entspannen mit Yoga","branding": "Intersport"},
                {"title": "Autonomer Notbremsassistent Er ortet Unfallrisiken, bevor Sie sie sehen.","branding": "Kia"},
                {"title": "Ho-ho-hol dir die besten Rabatte auf Deko, Betten und mehr","branding": "Wayfair"},
                {"title": "Apple iPhone 11 inklusive Apple AirPods und o2 Free M mit 20 GB für nur 51,99 € mtl.*","branding": "O2online"},
                {"title": "Europäische Datenökonomie- Hier erfährt Österreich mehr.","branding": "Zukunftindustrie"},
                {"title": "Totwinkelassistent mit Monitoranzeige Schutz vor unsichtbaren Gefahren.","branding": "Kia"},
                {"title": "Das Weihnachtsgewürz, bei dem die Kilos purzeln - Zimt zum Abnehmen!","branding": "Foodspring"},
                {"title": "Ausgeprägte Falten? Nachlassende Hautfestigkeit?","branding": "Haar-shop"},
                {"title": "Günstige Sportbekleidung & Sportartikel!","branding": "Otto"},
                {"title": "Angebote-Produkte & Zubehör online kaufen im INTERSPORT-Shop","branding": "Intersport"},
                {"title": "Kia Hybrid- und Elektromodelle","branding": "Kia"},
                {"title": "Machen Sie es sich schön! Unsere Themenwelten","branding": "Tchibo"},
                {"title": "Farbenfrohe Pieces und frühlingshafte Muster verpassen Deinem Kleiderschrank ein stylisches Spring-Update!","branding": "About You"},
                {"title": "Ab in den Schnee!","branding": "Tchibo"},
                {"title": "Angst vor Haarausfall? Tun Sie was dagegen.","branding": "Haar-shop"},
                {"title": "Der neue Freizeit-Chic Lässig-moderne Frühlingslooks für Sie und Ihn","branding": "Tchibo"},
                {"title": "Ein elektrisierendes Erlebnis: die Fahrzeuge der Kia e-Range","branding": "Kia"},
                {"title": "Die elektrifizierte Kia Niro Familie. Nichts geht über einen Niro.","branding": "Kia"},
                {"title": "Schmuddelwedda - Regenmäntel und Softshelljacken zu unglaublichen Preisen. Jetzt bei limango","branding": "Limango"},
                {"title": "Dieses Valentine's Special lässt dein Herz höherschlagen - jetzt entdecken!","branding": "Kapten-son"},
                {"title": "UGG Boots bis zu -62% reduziert. Solange der Vorrat reicht.","branding": "Limango"},
                {"title": "Diese Marken solltest Du Dir nicht entgehen lassen","branding": "About You"},
                {"title": "Erkunden Sie die wunderbare Welt von Swarovski. Herausragendes Styling seit 1895.","branding": "Swarovski"},
                {"title": "Motivation gefällig?","branding": "About You"},
                {"title": "Energetics: entspannen mit Yoga","branding": "Intersport"},
                {"title": "Dieser Möbel-Onlineshop wird dich umhauen","branding": "Wayfair"},
                {"title": "Ho-ho-hol dir die besten Rabatte auf Deko, Betten und mehr","branding": "Wayfair"},
                {"title": "Der Avène Thermalwasserspray… Ihr begleiter durch den Tag","branding": "Eau-thermale"},
                {"title": "Apple iPhone 11 inklusive Apple AirPods und o2 Free M mit 20 GB für nur 51,99 € mtl.*","branding": "O2online"},
                {"title": "Europäische Datenökonomie- Hier erfährt Österreich mehr.","branding": "Zukunftindustrie"},
                {"title": "Das Weihnachtsgewürz, bei dem die Kilos purzeln - Zimt zum Abnehmen!","branding": "Foodspring"},
                {"title": "Entdecke die Neuheiten Looks von Alife & Kickin Zum Shop","branding": "Otto"},
                {"title": "Ausgeprägte Falten? Nachlassende Hautfestigkeit?","branding": "Haar-shop"},
                {"title": "Angebote-Produkte & Zubehör online kaufen im INTERSPORT-Shop","branding": "Intersport"},
                {"title": "Kia Hybrid- und Elektromodelle","branding": "Kia"},
                {"title": "Angebote-Produkte & Zubehör online kaufen im INTERSPORT-Shop","branding": "Inter Sport"},
                {"title": "Diese Uhr ist derzeit heiß begehrt bei Influencern","branding": "Kapten-son"},
                {"title": "Dein So-wie-du-willst-Tarif mit unlimited Datenvolumen & Allnet-Flat für nur 39,99 € mtl.*","branding": "O2online"},
                {"title": "Schmuddelwedda - Regenmäntel und Softshelljacken zu unglaublichen Preisen. Jetzt bei limango","branding": "Limango"},
                {"title": "Jetzt mit 20 GB LTE im o2 Free M für nur 29,99 € mtl.*","branding": "O2online"},
                {"title": "Dein Studium mit 0%-Finanzierung vom Staat: So geht’s!","branding": "Bafög"},
                {"title": "Angst vor Haarausfall? Tun Sie was dagegen.","branding": "Renefurterer"},
                {"title": "Angesagte Themen Entdecke neue Trends","branding": "Otto"},
                {"title": "Happy Home Sports!","branding": "Tchibo"},
                {"title": "Ab in den Schnee!","branding": "Tchibo"},
                {"title": "Damenmode günstig im ABOUT YOU Sale kaufen","branding": "About You"},
                {"title": "Folge 3: Eine neue Eiskönigin bringt die Coach-Herzen zum Schmelzen","branding": "FRÜHSTÜCKSFERNSEHEN"},
                {"title": "Schluss mit hartnäckigen Unreinheiten!","branding": "Eau-thermale"},
                {"title": "Unsere Produkte werden nicht an Tieren getestet","branding": "Eau-thermale"},
                {"title": "2021 Tahun Keberuntungan dan Sempurna untuk Fokus pada Hubungan","branding": "Sindo News"},
                {"title": "5 Hal yang Tak Boleh Dilakukan Setelah Berhubungan Seks","branding": "CNN - Indonesia"},
                {"title": "7 Pemain yang Memiliki Gaya Bermain Mirip Diego Maradona","branding": "The Start Magazine"},
                {"title": "5 Kesalahan Saat Melakukan Seks Oral, Hindari Ya Bun","branding": "Hai Bunda"},
                {"title": "5 Zodiak yang Terkenal Genit, tapi Menawan","branding": "Sindo News"},
                {"title": "7 Pemain yang Bikin Manchester United Menyesal Melepas Mereka","branding": "The Start Magazine"},
                {"title": "Alasan Boeing Kena Denda Rp34 T atas Kecelakaan Lion Air","branding": "CNN - Indonesia"},
                {"title": "Alasan Cristiano Ronaldo Tak Kunjung Nikahi Georgina Rodriguez","branding": "Sindo News"},
                {"title": "Atta Halilintar Diamuk Ashanty Gara-gara Bikin Aurel Nangis","branding": "Hai Bunda"},
                {"title": "Belanja di OFS, Dapat Diskon s.d 80% Lho!","branding": "Selalu Official Store"},
                {"title": "Bisa dipasang langsung di rumah hanya dalam 2 menit, biaya sangat murah","branding": "Виниры индо 3"},
                {"title": "Bunda, 5 Tanaman Hias Cocok Buat Kamar Bikin Tidur Nyenyak","branding": "CNBC - Indonesia"},
                {"title": "Cantik & Tajir, Ini 7 Eksekutif Perempuan Anak Konglomerat RI","branding": "CNBC - Indonesia"},
                {"title": "Diskon besar-besaran veneer gigi lepas pasang!","branding": "Виниры индо 3"},
                {"title": "Diusir dari Restoran karena Pakai Bra, Backpacker Ini Marah","branding": "Sindo News"},
                {"title": "Gembok Cakram Motor Original HONDA Disk Look","branding": "Tokopedia"},
                {"title": "Gisel Mengaku Sedang Mabuk Saat Rekam Video Syur","branding": "The Start Magazine"},
                {"title": "Heboh Nakes Wafat Mendadak 2 Hari Usai Divaksin Pfizer","branding": "CNBC - Indonesia"},
                {"title": "Hewan Ini Melakukan 'Pesta' Seks Sampai Mati","branding": "CNN - Indonesia"},
                {"title": "Positif Corona, Salah Dikecam Saat Berdansa Tanpa Masker","branding": "CNN - Indonesia"},
                {"title": "KNK Rak Tanaman Hias Besi Gantung Rak Pot Bunga Besi Gantung - Hitam","branding": "Tokopedia"},
                {"title": "Manfaat Jalan Kaki untuk Ibu Hamil, Bunda Perlu Tahu","branding": "Hai Bunda"},
                {"title": "Jajan Makanan & Minuman Cashback s.d. 90% Lho","branding": "Tokopedia"},
                {"title": "Mau Diskon 80% Untuk Kebutuhan Kendaraanmu?","branding": "Tokopedia"},
                {"title": "Pengasuh Tega Perkosa Bocah Lelaki 11 Tahun, Kini Punya Anak Balita","branding": "Hai Bunda"},
                {"title": "Pepes Bandeng Presto - Frozen Food Premium - Pete","branding": "Tokopedia"},
                {"title": "Rak Jemuran Baju Pakaian Gantung Besi Rak Standing Double Clothes 999 - Hitam, 2-TIANG","branding": "Tokopedia"},
                {"title": "Satu keluarga, tiga waria: 'saya punya anak tiga banci ini, Tuhan yang buat'","branding": "The Start Magazine"},
                {"title": "Senang Mengenal Gading Marten, Karen Nijsen: Kita Lagi Dekat...","branding": "Sindo News"},
                {"title": "Kesunyian dalam Menghadapi Kematian","branding": "The Start Magazine"},
                {"title": "Snap-On Smile - lapisan yang nyaman dan ringan","branding": "Виниры индо 3"},
                {"title": "Teddy Ngotot Minta Warisan Lina, Sule Beri Balasan Menohok, Singgung Harta yang Sudah Dijual Teddy - Tribun Bali","branding": "The Start Magazine"},
                {"title": "tempered glass Sony A6600 A6500 A6000 A6300 A6400 anti gores screen","branding": "Tokopedia"},
                {"title": "Terbongkar! Alasan Sebenarnya Mengapa Gisel Bikin Video Syur Bareng MYD, Padahal Masih Status Istri - Tribun Timur","branding": "The Start Magazine"},
                {"title": "Tujuh Hal yang sama Sekali Tidak Seksi Tentang Seks","branding": "CNN - Indonesia"},
                {"title": "Halloween: Tot €200 korting","branding": "Acer"},
                {"title": "Cadeau kopen? Altijd scherp geprijsd en online besteld!","branding": "Bol.com"},
                {"title": "Birkenstock de slippers van het moment, nu sterk afgeprijsd bij limango.","branding": "Limango"},
                {"title": "Breng je bureaublad tot leven met deze prachtige wallpapers","branding": "Microsoft"},
                {"title": "Download de Microsoft Nieuws app om altijd op de hoogte te blijven","branding": "MSN"},
                {"title": "Grote maten mode in stijl: nu exclusief -20% op duurste product","branding": "Peter Hahn"},
                {"title": "Exclusief: 20% korting op het duurste product in dames- en herenmode.","branding": "Tradedoubler"},
                {"title": "Lees het volgende voordat je een maaltijdbox bestelt","branding": "Trueself"},
                {"title": "Tijdelijke aanbieding: nu in totaal €40,- korting op je eerste 3 boxen!","branding": "Peter Hahn"},
                {"title": "Download nu Edge, de nieuwe browser van Microsoft","branding": "Microsoft"},
                {"title": "Tot -50% op speelgoed! Dé online speelgoed outlet.","branding": "Bol.com"},
                {"title": "Ontdek de wereld met deze prachtige wallpaper-foto’s van Bing","branding": "Microsoft"},
                {"title": "Tijdelijk tot -30% op de nieuwe dames collectie bij Peter Hahn!","branding": "Peter Hahn"},
                {"title": "Birkenstock tot -70% korting. Nu ontdekken.","branding": "Limango"},
                {"title": "Breng je bureaublad tot leven met deze prachtige wallpapers","branding": "Microsoft"},
                {"title": "De klassieke, kleurrijke en originele modellen van Vans tot -64% korting.","branding": "Limango"},
                {"title": "Breng je bureaublad tot leven met je favoriete wallpapers","branding": "Microsoft"},
                {"title": "Cadeau kopen? Altijd scherp geprijsd en online besteld!","branding": "Bol.com"},
                {"title": "Download de Microsoft Nieuws app om altijd op de hoogte te blijven","branding": "Microsoft"},
                {"title": "Bestel scheerproducten mét korting online! Ontdek het hier.","branding": "Bol.com"},
                {"title": "Download nu Edge, de nieuwe browser van Microsoft","branding": "Microsoft"},
                {"title": "Een must-have voor iedere professionele kok. JosephJoseph tot -50% korting.","branding": "Limango"},
                {"title": "Alles voor het tuinieren, maar dan mét korting! Bestel online.","branding": "Bol.com"},
                {"title": "Exclusief: 20% korting op het duurste product in dames- en herenmode.","branding": "Peter Hahn"},
                {"title": "Fraaie Bing achtergrondfoto’s van over de hele wereld","branding": "Microsoft"},
                {"title": "Gamefreak? Ontdek de acties nu online!","branding": "Bol.com"},
                {"title": "Herfstaanbieding: 50% korting op je eerste twee HelloFresh Boxen","branding": "Peter Hahn"},
                {"title": "Het leukste schoenenmerk voor elke vrouw van Birkenstock. Nu tot -70% korting.","branding": "Limango"},
                {"title": "Breng je bureaublad tot leven met Bing wallpapers","branding": "Microsoft"},
                {"title": "Keukenbenodigdheden die iedere masterchef nodig heeft. JosephJoseph tot -50% korting.","branding": "Limango"},
                {"title": "Lees het volgende voordat je een maaltijdbox bestelt","branding": "MSN"},
                {"title": "Ontdek de wereld met deze prachtige wallpaper-foto’s van Bing","branding": "Microsoft"},
                {"title": "Op zoek naar een goed boek? Ontdek ze hier, mét korting!","branding": "Bol.com"},
                {"title": "Prachtige achtergrondfoto’s van over de hele wereld","branding": "Microsoft"},
                {"title": "Tijdelijk tot -30% op de nieuwe dames collectie bij Peter Hahn!","branding": "Peter Hahn"},
                {"title": "Tijdelijke aanbieding: nu in totaal €40,- korting op je eerste 3 boxen!","branding": "Hello Fresh"},
                {"title": "Tot -30% op dames mode? Peter Hahn trakteerd met korting op mode!","branding": "Peter Hahn"},
                {"title": "Tot -50% op alles voor het huishouden! Bestel makkelijk online.","branding": "Bol.com"},
                {"title": "Tot -50% op speelgoed! Dé online speelgoed outlet.","branding": "Bol.com"},
                {"title": "Tot -50% op uw dagelijkse producten! Ontdek het online.","branding": "Bol.com"},
                {"title": "Tot €200 korting","branding": "Acer"},
                {"title": "Comfortabel en voordelig, Toms nu tijdelijk sterk afgeprijsd bij limango.","branding": "Limango"},
                {"title": "Een must-have voor iedere professionele kok. JosephJoseph tot -50% korting.","branding": "Limango"},
                {"title": "JosephJoseph tot -50% korting. Nu ontdekken.","branding": "Limango"},
                {"title": "Toms, de zomerschoenen van het moment. Nu sterk afgeprijsd bij limango.","branding": "Limango"},
                {"title": "UGG laarzen tot -70% afgeprijsd. Zolang de voorraad strekt.","branding": "Limango"},
                {"title": "Moderne schoenen van UGG tot -70%* afgeprijsd. Nu ontdekken.","branding": "Limango"},
                {"title": "Muchachomalo nu beschikbaar bij limango, sterk afgeprijsd.","branding": "Limango"},
                {"title": "Keukenbenodigdheden die iedere masterchef nodig heeft. JosephJoseph tot -50% korting.","branding": "Limango"},
                {"title": "Keukenbenodigdheden van JosephJoseph tot -50% korting. Nu ontdekken.","branding": "Limango"},
                {"title": "Nike tot -48% korting. Zolang de voorraad strekt.","branding": "Limango"},
                {"title": "Nike tot -70% korting. Zolang de voorraad strekt.","branding": "Limango"},
                {"title": "Puma Mode, nu sterk afgeprijsd bij limango. Kijk nu snel in de online shop voor het aanbod","branding": "Limango"},
                {"title": "Rugzakken & Tassen van Eastpak tot -70% korting. Zolang de voorraad strekt.","branding": "Limango"},
                {"title": "Sapph tot 70% korting verkrijgbaar bij limango, wees er snel bij.","branding": "Limango"},
                {"title": "Sportmode voor hem en haar tot -70% korting. Nu ontdekken","branding": "Limango"},
                {"title": "Stijlvolle en kleurrijke schoenen van het bekende merk. Vans tot -64% korting.","branding": "Limango"},
                {"title": "En dagbok om ett DNA-test","branding": "Ancestry"},
                {"title": "Din pålitliga och professionella bilköpare: viköperdinbil.se","branding": "vikoperdinbil.se"},
                {"title": "Världens största sökmotor för semesterboenden.","branding": "Home to Go"},
                {"title": "Jämför flygresor Hitta billiga flyg genom att jämföra alla flygbiljettpriser","branding": "Jetcost"},
                {"title": "Ditt drömhotell till det bästa priset","branding": "Hotel Scan"},
                {"title": "Hitta det bästa och billigaste elavtalet i ditt område.","branding": "el.se"},
                {"title": "Världens 15 Farligaste Vägar","branding": "Buhamster"},
                {"title": "Sök och jämför över 1,8 miljoner produkter från 5 900 butiker","branding": "Price Runner"},
                {"title": "Tips På Hur Man Kan Jämföra Finansieringsofferter","branding": "3 Step It"},
                {"title": "Smart sminkborstrengörare Shoppa nu","branding": "Shopido"},
                {"title": "Tusentals använder gurkmeja för artritsmärta, men detta har en livsförändrande bieffekt.","branding": "LifestyleMag"},
                {"title": "Vad du ska tänka på när du väljer mobilabonnemang","branding": "MegaSavings"},
                {"title": "AUTODOC — Auto Parts at Low Prices Online","branding": "AUTODOC"},
                {"title": "Senaste Tech: Otroligt nytt säkerhetssystem har fått gott rykte över hela världen","branding": "DailyTechTrend"},
                {"title": "Banbrytande enhet fixar problemen med långsamt WiFi och avslöjar snikna Internetleverantörer","branding": "TheGadgetReviewGuy"},
                {"title": "Den Här Genialiska Enheten Gör Att Du Kan Kommunicera På Över 40 Språk","branding": "SmartNewTrends"},
                {"title": "Välkommen till casino vinnaren - en plats för dig som vill spela casino online","branding": "Casinovinnaren"},
                {"title": "Revolutionerande säkerhetssystem som kopplar din mobil till ditt larmsystem","branding": "Expert Market"},
                {"title": "Kan du identifiera dessa kända historiska personer?","branding": "Buquiz"},
                {"title": "Så väljer du den bästa vinteroverallen - testvinnarna som säljer slut!","branding": "Price Runner"},
                {"title": "Jag gjorde Ancestrys DNA-test. Detta är vad jag fick reda på.","branding": "Ancestry"},
                {"title": "Hitta äntligen den perfekta nattsömnen med velux gardiner","branding": "Mega Savings"},
                {"title": "Det är i grunden förvånansvärt enkelt att byta elbolag. Ofta handlar det bara om ett telefonsamtal eller ett par knapptryckningar på datorn. Men det finns några saker du ska se upp med.","branding": "El.se"},
                {"title": "Nu behöver ingen vänta på att få sin cancer behandlad","branding": "Docrates"},
                {"title": "En fantastisk skärm som räcker hela dagen","branding": "Dell"},
                {"title": "Få offerter från kontrollerade och betygsatta flyttfirmor. Jämför priser från vårt omfattande partnernätverk","branding": "Din Flytt"},
                {"title": "Du kommer att älska den här argentinska regionen som bjuder på spännande utmaningar och fantastiska kameramotiv.","branding": "G Adventures"},
                {"title": "25 hänslående foton som inte fått hjälp av photoshop","branding": "Buhamster"},
                {"title": "Få erbjudanden på larm från flera företag","branding": "Larm"},
                {"title": "En uppkoppling som inte fungerar påverkar både medarbetaren och organisationen.","branding": "Telia"},
                {"title": "Kraftkvinnorna för samman affärsnytta med jämställdhet","branding": "Bransch Aktuellt"},
                {"title": "Skapa din egen hemsida med tre enkla steg","branding": "Simplesite"}
            ];

            let selector = "video-label-box trc-main-label";
            let titleConatiner = document.getElementsByClassName(selector);

            // console.log("content page details : ", titleConatiner);
            for (i=0; i<titleConatiner.length; i++) {
                // console.log(titleConatiner[i].children[0].innerHTML);

                let obj = brandingObjectArray.find(o => o.title == titleConatiner[i].children[0].innerHTML);

                //{"title": "Hot or Not: Europeans Named the Hottest on the Sand","branding": "Expedia"},
                // console.log(obj);
                if (obj !== undefined) {
                    titleConatiner[i].children[2].children[0].innerHTML = obj.branding;
                    // console.log(titleConatiner[i].children[2].children[0]);
                }
                // titleConatiner[i].innerHTML = "<span>"+languageList[p.selectedLanguage]+"</span>";
                // console.log("content page details : ", brandings[i]);
                // break;
            }
        }


        methods.changeCompositeBranding = function (p) {

            let languageList = {
                "English":"Sponsored",
                "Hebrew":"ממומן",
                "Spanish":"Patrocinado",
                "French":"Sponsorisé",
                "German":"Gesponsert",
                "Portugese":"Patrocinado",
                "Japanese":"スポンサー",
                "Chinese":"提供",
                "Korean":"추천된",
                "Dutch":"Gesponsord", 
                "Polish":"Sponsorowane",
                "Italian":"Sponsorizzato",
                "Russian":"Спонсируется",
                "Turkish":"Sponsorlu",
                "Thai":"สปอนเซอร์", 
                "Dannish":"annoncørbetalt indhold"
            };

            let mostPopularList = {
                "English":"MOST POPULAR",
                "Hebrew":"הכי פופולארי",
                "Spanish":"MÁS POPULAR",
                "French":"LES PLUS LUS",
                "German":"AM BELIEBTESTEN",
                "Portuguese":"MAIS POPULAR",
                "Japanese":"最も人気のある",
                "Chinese":"最受歡迎",
                "Korean":"가장 인기있는",
                "Dutch":"MEEST POPULAIR",
                "Polish":"NAJBARDZIEJ POPULARNY",
                "Italian":"PIÙ POPOLARE",
                "Russian":"САМЫЙ ПОПУЛЯРНЫЙ",
                "Turkish":"EN POPÜLER",
                "Thai":"ที่นิยมมากที่สุด",
                "Danish":"MEST POPULÆRE"
            };

            let selector = "trc_desktop_disclosure_link trc_attribution_position_after_branding";
            let brandings = document.getElementsByClassName(selector);

            //css
            let cssString = `.organic-thumbs-feed-01-mp div.trc_rbox_outer div.videoCube span.thumbBlock:after {
                content: "${mostPopularList[p.selectedLanguage]}";
            }`;

            let style = document.createElement('style');
            style.type = 'text/css';

            if (style.styleSheet) { // IE
                style.styleSheet.cssText = cssString;
            } else {
                style.appendChild(document.createTextNode(cssString));
            }

            document.getElementsByTagName('head')[0].appendChild(style);
            //css end

            // console.log("content page details : ", brandings);
            for (i=0; i<brandings.length; i++) {
                brandings[i].innerHTML = "<span>"+languageList[p.selectedLanguage]+"</span>";
                // console.log("content page details : ", brandings[i]);
            }

            let mobileSelector = "trc_mobile_disclosure_link trc_attribution_position_after_branding";
            let mobileBrandings = document.getElementsByClassName(mobileSelector);
            // console.log("content page details : ", mobileBrandings);
            for (i=0; i<mobileBrandings.length; i++) {
                mobileBrandings[i].innerHTML = "<span>"+languageList[p.selectedLanguage]+"</span>";
                // console.log("content page details : ", mobileBrandings[i]);
            }

            // chrome.tabs.query({active: true, currentWindow: true}, function (tabs) {
            //     chrome.tabs.insertCSS(tabs[0].id, {code: cssString});
            // });
        }


        function clear() {

        }


// This tells the script to listen for
// messages from our extension.
        chrome.runtime.onMessage.addListener(function (request, sender, sendResponse) {

            //console.log("Request is " + request.method);

            if (request.method == "changeCompositeBranding") {
                var params = request.params;
                //console.log(methods.checkSelector(request.params));
                sendResponse(methods.changeCompositeBranding(params));
                return (true);
            }

            if (request.method == "updateNativeBranding") {
                var params = request.params;
                sendResponse(methods.updateNativeBranding(params));
                return true;
            }

            return true;
        })
    })()
